Revert "Export to global scope in server or embedded environments"
This reverts commit aae2099e8426922af269adde9e064e70511dbe77.
  aae2099 was originally merged by be92738a1a928

While this change passes tests, it breaks twitter.com with:
"Uncaught TypeError: undefined is not a function"

Hopefully those who need this can maintain their own fork for now.